# Generated by Django 5.1.5 on 2025-01-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('course', models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('ENG', 'Engineering'), ('MATH', 'Mathematics'), ('BIO', 'Biology')], max_length=50)),
            ],
        ),
    ]
